##The following two properties should be set for every design
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]

set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_n]
set_property PACKAGE_PIN AP40 [get_ports sys_rst_n]
set_property PACKAGE_PIN AU36 [get_ports uart_txd]
set_property PACKAGE_PIN AU33 [get_ports uart_rxd]
set_property SLEW SLOW [get_ports uart_txd]
set_property DRIVE 12 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS18 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]

set_property IOSTANDARD LVCMOS18 [get_ports led0]
set_property IOSTANDARD LVCMOS18 [get_ports led1]
set_property IOSTANDARD LVCMOS18 [get_ports led2]
set_property IOSTANDARD LVCMOS18 [get_ports led3]
set_property IOSTANDARD LVCMOS18 [get_ports led4]
set_property IOSTANDARD LVCMOS18 [get_ports led5]
set_property IOSTANDARD LVCMOS18 [get_ports led6]
set_property IOSTANDARD LVCMOS18 [get_ports led7]
set_property PACKAGE_PIN AM39 [get_ports led0]
set_property PACKAGE_PIN AN39 [get_ports led1]
set_property PACKAGE_PIN AR37 [get_ports led2]
set_property PACKAGE_PIN AT37 [get_ports led3]

set_property PACKAGE_PIN AP41 [get_ports led5]
set_property PACKAGE_PIN H19 [get_ports sys_clk_p]

set_property PACKAGE_PIN AR40 [get_ports sw1]
set_property IOSTANDARD LVCMOS18 [get_ports sw1]
set_property PACKAGE_PIN AU38 [get_ports sw2]
set_property IOSTANDARD LVCMOS18 [get_ports sw2]
set_property PACKAGE_PIN AR35 [get_ports led4]
set_property PACKAGE_PIN AP42 [get_ports led6]
set_property PACKAGE_PIN AU39 [get_ports led7]

